import { Group, GroupState } from '@types';

export const dummyData: Group[] = [
  {
    id: 1,
    mentorId: 1010,
    ownerId: 2020,
    name: 'REACT',
    maxUserCnt: 5,
    curUserCnt: 2,
    intro: '안녕하세요 어서오세요',
    startAt: new Date(),
    endAt: new Date(),
    status: GroupState.DOING,
  },
  {
    id: 142,
    mentorId: 102410,
    ownerId: 2022340,
    name: 'HAPPY',
    maxUserCnt: 10,
    curUserCnt: 1,
    intro: 'HAPPY 하네용',
    startAt: new Date(),
    endAt: new Date(),
    status: GroupState.DOING,
  },
  {
    id: 155,
    mentorId: 1010,
    ownerId: 2020,
    name: 'Express',
    maxUserCnt: 5,
    curUserCnt: 2,
    intro: 'Express 배워봅시다!',
    startAt: new Date(),
    endAt: new Date(),
    status: GroupState.DOING,
  },
  {
    id: 124,
    mentorId: 1010,
    ownerId: 2020,
    name: '알고리즘',
    maxUserCnt: 5,
    curUserCnt: 2,
    intro: '백준 하루에 10문제',
    startAt: new Date(),
    endAt: new Date(),
    status: GroupState.DOING,
  },
  {
    id: 11,
    mentorId: 1010,
    ownerId: 2020,
    name: '프로젝트 진행!',
    maxUserCnt: 5,
    curUserCnt: 2,
    intro: '프로젝트원 구합니다!',
    startAt: new Date(),
    endAt: new Date(),
    status: GroupState.DOING,
  },
];
