export enum ToastMessageEnum {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
}

export enum LeftOrRight {
  LEFT,
  RIGHT,
}

export enum MentorOrMentee {
  MENTOR = 'MENTOR',
  MENTEE = 'MENTEE',
}

export enum NotificationTypeEnum {
  JOIN_GROUP_REQUEST = 'JOIN_GROUP_REQUEST',
  MENTORING_REQUEST = 'MENTORING_REQUEST',
  JOIN_GROUP_ACCEPTED = 'JOIN_GROUP_ACCEPTED',
  JOIN_GROUP_DECLINED = 'JOIN_GROUP_DECLINED',
  MENTORING_ACCEPTED = 'MENTORING_ACCEPTED',
  METTORING_DECLIEND = 'METTORING_DECLIEND',
}
